### ISSUE TITLE
Todo list app

### ISSUE THREAD

**Issue by mozgovipc** [mozgovipc/todo#1]
## Why
I want to implement a todo list app using angularjs.

## What
- [x] Cleanup the seed project and adapt it to a single-view mode
- [x] Add todo service that holds the todo items and provides add/remove/update methods on todo items. Simple array for now. Data is not saved anywhere
- [x] Create todo master view/controller, it displays only a count of todo items
- [x] Create todo item directive with done/undone actions
- [x] Adjust the todo service to load/save the todo items from the browser local storage
- [x] Implement adding todo item
- [x] removing todo item
- [x] Implement filtering by status (all, active, done)
